name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Create theme zip
        run: |
          apt-get update && apt-get install -y zip
          zip -r finnimal.zip parts patterns templates functions.php README.md style.css theme.json
      - uses: softprops/action-gh-release@v2
        with:
          files: finnimal.zip
